### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by penggaolai** [cerner/cds-services-tutorial#19]
I tried to build the docker image, I got following error:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch
":"any"} (current: {"os":"linux","arch":"x64"})

Since it is warning, I thought it would be ok. But I couldn't connect to the site. Any suggestion how to fix this? Thank you.

**Comment by dennispatterson** [comment]
The tutorial uses [nodemon](https://github.com/remy/nodemon) to automatically restart the server when you change code.  Under the covers, it uses [chokidar](https://github.com/paulmillr/chokidar#how), which provides cross-platform functionality to monitor for file changes.  For MacOS, this means using [fsevents](https://github.com/fsevents/fsevents).  For other operating systems, it uses alternate means.  Since you're on linux, it rightfully skips fsevents and logs that benign warning.
